### ISSUE TITLE
output number of train_val.prototxt

### ISSUE THREAD

**Issue by luoyetx** [sciencefans/Beyond-Frontal-Faces#1]
Since the training data only has 1409 different identities, the output number of fc8 should be 1409 not 2356. Am I right?

https://github.com/sciencefans/Beyond-Frontal-Faces/blob/master/caffe_model%2Ftrain_val.prototxt#L298

By the way, did you train the body and head network using the same structure like train_val.prototxt?

Thanks.

**Comment by liuyuisanai** [comment]
@luoyetx Yes for both questions. BTW, this project was done in 2015, so the prototxt is out of date(V1 vs V2), you need to convert it using the convert tool in caffe.

**Comment by luoyetx** [comment]
Thanks for your reply :)
